linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_print: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    diagnostic_describe_all_properties: true
    directives_ordering: true
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: false
    implementation_imports: true
    # invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    # missing_required_param: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    # prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    recursive_getters: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true

    # unused_import: true

analyzer:
  errors:
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    always_use_package_imports: ignore
    annotate_overrides: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: warning
    avoid_double_and_int_checks: error
    avoid_dynamic_calls: warning
    avoid_empty_else: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_escaping_inner_quotes: ignore
    avoid_field_initializers_in_const_classes: error
    avoid_function_literals_in_foreach_calls: ignore
    avoid_implementing_value_types: error
    avoid_init_to_null: error
    avoid_js_rounded_ints: error
    avoid_multiple_declarations_per_line: error
    avoid_null_checks_in_equality_operators: error
    avoid_positional_boolean_parameters: warning
    avoid_print: info
    avoid_private_typedef_functions: error
    avoid_redundant_argument_values: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: ignore
    avoid_return_types_on_setters: error
    avoid_returning_null: error
    avoid_returning_null_for_future: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: error
    avoid_slow_async_io: error
    avoid_type_to_string: error
    avoid_types_as_parameter_names: error
    avoid_unnecessary_containers: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: info
    cancel_subscriptions: error
    cascade_invocations: ignore
    cast_nullable_to_non_nullable: error
    close_sinks: error
    comment_references: warning
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: error
    deprecated_consistency: info
    diagnostic_describe_all_properties: ignore
    directives_ordering: ignore
    do_not_use_environment: error
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: warning
    exhaustive_cases: error
    file_names: error
    #    flutter_style_todos: error
    implementation_imports: ignore
    invariant_booleans: error
    iterable_contains_unrelated_type: error
    join_return_with_assignment: error
    leading_newlines_in_multiline_strings: error
    library_names: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning
    missing_required_param: error
    missing_whitespace_between_adjacent_strings: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    no_runtimeType_toString: error
    noop_primitive_operations: error
    null_check_on_nullable_type_parameter: error
    null_closures: error
    omit_local_variable_types: ignore
    one_member_abstracts: error
    only_throw_errors: error
    overridden_fields: error
    package_api_docs: error
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: error
    prefer_asserts_in_initializer_lists: error
    prefer_asserts_with_message: ignore
    prefer_collection_literals: warning
    prefer_conditional_assignment: error
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: warning
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: info
    prefer_for_elements_to_map_fromIterable: error
    prefer_foreach: error
    prefer_function_declarations_over_variables: info
    prefer_generic_function_type_aliases: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_is_not_operator: error
    prefer_iterable_whereType: error
    prefer_mixin: info
    prefer_null_aware_method_calls: warning
    prefer_null_aware_operators: error
    # prefer_relative_imports: ignore
    prefer_single_quotes: warning
    prefer_spread_collections: error
    prefer_typing_uninitialized_variables: error
    prefer_void_to_null: error
    provide_deprecation_message: error
    recursive_getters: error
    require_trailing_commas: info
    sized_box_for_whitespace: error
    slash_for_doc_comments: error
    sort_child_properties_last: ignore
    sort_pub_dependencies: ignore
    sort_unnamed_constructors_first: error
    test_types_in_equals: error
    throw_in_finally: error
    tighten_type_of_initializing_formals: error
    type_init_formals: error
    unawaited_futures: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: info
    unnecessary_const: error
    unnecessary_getters_setters: ignore
    unnecessary_lambdas: info
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_checks: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_raw_strings: error
    unnecessary_statements: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    unrelated_type_equality_checks: error
    unsafe_html: error
    use_build_context_synchronously: ignore
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    use_if_null_to_convert_nulls_to_bools: error
    use_is_even_rather_than_modulo: error
    use_key_in_widget_constructors: info
    use_late_for_private_fields_and_variables: error
    use_named_constants: warning
    use_raw_strings: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: error
    use_string_buffers: error
    use_test_throws_matchers: error
    use_to_and_as_if_applicable: error
    valid_regexps: error
    void_checks: error
    unused_import: info

  exclude:
    - common_sub/sql_lite_database/qr_code_db/lib/src/drift.g.dart
    - common_sub/sql_lite_database/s4h_inventory_db/lib/src/drift.g.dart
    - common_sub/v_intl_phone_number_input/lib/src/sys/**
